language: es
pipeline:
# Procesamiento de lenguaje natural en español (DEBE ir primero)
- name: SpacyNLP
  model: "es_core_news_sm"
# Tokenización específica para español (requiere SpacyNLP)
- name: SpacyTokenizer
# Características léxicas y sintácticas
- name: LexicalSyntacticFeaturizer
# Características de regex
- name: RegexFeaturizer
# Vectorización de palabras para español
- name: CountVectorsFeaturizer
  analyzer: "word"
  min_ngram: 1
  max_ngram: 2
# Vectorización de caracteres para capturar variaciones morfológicas del español
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
# Clasificador DIET optimizado para español
- name: DIETClassifier
  epochs: 50
  batch_size: 128
  evaluate_every_number_of_epochs: 10
  constrain_similarities: true

# Mapeo de sinónimos de entidades
- name: EntitySynonymMapper

# Clasificador de fallback
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
  max_history: 3
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
  max_history: 3
- name: TEDPolicy
  max_history: 3
  epochs: 50
  batch_size: 128
  evaluate_every_number_of_epochs: 10
assistant_id: 20231121-211621-relaxed-bookshelf