services:
  rasa-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "5055:5055"
    environment:
      - SQLALCHEMY_WARN_20=0
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    env_file:
      - .env
    volumes:
      - ./models:/app/models